Interactive Visual Analytics with Folium

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using matplotlib and seaborn and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using Folium.
Objectives

This lab contains the following tasks:

    TASK 1: Mark all launch sites on a map
    TASK 2: Mark the success/failed launches for each site on the map
    TASK 3: Calculate the distances between a launch site to its proximities

In [3]:
import folium
import pandas as pd

In [4]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon


from folium import plugins

In [5]:
spacex_df=pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv')

In [6]:
spacex_df.head(20)

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
5,7,2013-12-03,22:41:00,F9 v1.1,CCAFS LC-40,SES-8,3170.0,GTO,SES,No attempt,0,28.562302,-80.577356
6,8,2014-01-06,22:06:00,F9 v1.1,CCAFS LC-40,Thaicom 6,3325.0,GTO,Thaicom,No attempt,0,28.562302,-80.577356
7,9,2014-04-18,19:25:00,F9 v1.1,CCAFS LC-40,SpaceX CRS-3,2296.0,LEO (ISS),NASA (CRS),Controlled (ocean),0,28.562302,-80.577356
8,10,2014-07-14,15:15:00,F9 v1.1,CCAFS LC-40,OG2 Mission 1 6 Orbcomm-OG2 satellites,1316.0,LEO,Orbcomm,Controlled (ocean),0,28.562302,-80.577356
9,11,2014-08-05,8:00:00,F9 v1.1,CCAFS LC-40,AsiaSat 8,4535.0,GTO,AsiaSat,No attempt,0,28.562302,-80.577356
10,12,2014-09-07,5:00:00,F9 v1.1 B1011,CCAFS LC-40,AsiaSat 6,4428.0,GTO,AsiaSat,No attempt,0,28.562302,-80.577356
11,13,2014-09-21,5:52:00,F9 v1.1 B1010,CCAFS LC-40,SpaceX CRS-4,2216.0,LEO (ISS),NASA (CRS),Uncontrolled (ocean),0,28.562302,-80.577356
12,14,2015-01-10,9:47:00,F9 v1.1 B1012,CCAFS LC-40,SpaceX CRS-5,2395.0,LEO (ISS),NASA (CRS),Failure (drone ship),0,28.562302,-80.577356
13,15,2015-02-11,23:03:00,F9 v1.1 B1013,CCAFS LC-40,DSCOVR,570.0,Sun–Earth L1,U.S. Air Force NASA NOAA,Controlled (ocean),0,28.562302,-80.577356
14,16,2015-03-02,3:50:00,F9 v1.1 B1014,CCAFS LC-40,ABS-3A Eutelsat 115 West B,4159.0,GTO,ABS Eutelsat,No attempt,0,28.562302,-80.577356
15,17,2015-04-14,20:10:00,F9 v1.1 B1015,CCAFS LC-40,SpaceX CRS-6,1898.0,LEO (ISS),NASA (CRS),Failure (drone ship),0,28.562302,-80.577356
16,18,2015-04-27,23:03:00,F9 v1.1 B1016,CCAFS LC-40,TürkmenÄlem 52°E / MonacoSAT,4707.0,GTO,Turkmenistan National Space Agency,No attempt,0,28.562302,-80.577356
17,19,2015-06-28,14:21:00,F9 v1.1 B1018,CCAFS LC-40,SpaceX CRS-7,1952.0,LEO (ISS),NASA (CRS),Precluded (drone ship),1,28.562302,-80.577356
18,20,2015-12-22,1:29:00,F9 FT B1019,CCAFS LC-40,OG2 Mission 2 11 Orbcomm-OG2 satellites,2034.0,LEO,Orbcomm,Success (ground pad),1,28.562302,-80.577356
19,22,2016-03-04,23:35:00,F9 FT B1020,CCAFS LC-40,SES-9,5271.0,GTO,SES,Failure (drone ship),0,28.562302,-80.577356

In [7]:
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

In [8]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [9]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

In [10]:
m = folium.Map(location = nasa_coordinate, zoom_start = 10)

ss_map = plugins.MarkerCluster().add_to(m)

for lat, long, region in zip(launch_sites_df['Lat'], launch_sites_df['Long'], launch_sites_df['Launch Site']):
    folium.Marker(
        location = [lat, long],
        icon = None,
        popup = region,
    ).add_to(ss_map)

In [11]:
spacex_df

     Launch Site        Lat        Long  class
0    CCAFS LC-40  28.562302  -80.577356      0
1    CCAFS LC-40  28.562302  -80.577356      0
2    CCAFS LC-40  28.562302  -80.577356      0
3    CCAFS LC-40  28.562302  -80.577356      0
4    CCAFS LC-40  28.562302  -80.577356      0
5    CCAFS LC-40  28.562302  -80.577356      0
6    CCAFS LC-40  28.562302  -80.577356      0
7    CCAFS LC-40  28.562302  -80.577356      0
8    CCAFS LC-40  28.562302  -80.577356      0
9    CCAFS LC-40  28.562302  -80.577356      0
10   CCAFS LC-40  28.562302  -80.577356      0
11   CCAFS LC-40  28.562302  -80.577356      0
12   CCAFS LC-40  28.562302  -80.577356      0
13   CCAFS LC-40  28.562302  -80.577356      0
14   CCAFS LC-40  28.562302  -80.577356      0
15   CCAFS LC-40  28.562302  -80.577356      0
16   CCAFS LC-40  28.562302  -80.577356      0
17   CCAFS LC-40  28.562302  -80.577356      1
18   CCAFS LC-40  28.562302  -80.577356      1
19   CCAFS LC-40  28.562302  -80.577356      0
20   CCAFS LC-40  28.562302  -80.577356      1
21   CCAFS LC-40  28.562302  -80.577356      1
22   CCAFS LC-40  28.562302  -80.577356      1
23   CCAFS LC-40  28.562302  -80.577356      0
24   CCAFS LC-40  28.562302  -80.577356      1
25   CCAFS LC-40  28.562302  -80.577356      1
26   VAFB SLC-4E  34.632834 -120.610745      0
27   VAFB SLC-4E  34.632834 -120.610745      0
28   VAFB SLC-4E  34.632834 -120.610745      1
29   VAFB SLC-4E  34.632834 -120.610745      1
30   VAFB SLC-4E  34.632834 -120.610745      1
31   VAFB SLC-4E  34.632834 -120.610745      1
32   VAFB SLC-4E  34.632834 -120.610745      0
33   VAFB SLC-4E  34.632834 -120.610745      0
34   VAFB SLC-4E  34.632834 -120.610745      0
35   VAFB SLC-4E  34.632834 -120.610745      0
36    KSC LC-39A  28.573255  -80.646895      1
37    KSC LC-39A  28.573255  -80.646895      0
38    KSC LC-39A  28.573255  -80.646895      1
39    KSC LC-39A  28.573255  -80.646895      1
40    KSC LC-39A  28.573255  -80.646895      0
41    KSC LC-39A  28.573255  -80.646895      1
42    KSC LC-39A  28.573255  -80.646895      1
43    KSC LC-39A  28.573255  -80.646895      0
44    KSC LC-39A  28.573255  -80.646895      1
45    KSC LC-39A  28.573255  -80.646895      1
46    KSC LC-39A  28.573255  -80.646895      1
47    KSC LC-39A  28.573255  -80.646895      1
48    KSC LC-39A  28.573255  -80.646895      1
49  CCAFS SLC-40  28.563197  -80.576820      1
50  CCAFS SLC-40  28.563197  -80.576820      1
51  CCAFS SLC-40  28.563197  -80.576820      0
52  CCAFS SLC-40  28.563197  -80.576820      0
53  CCAFS SLC-40  28.563197  -80.576820      0
54  CCAFS SLC-40  28.563197  -80.576820      1
55  CCAFS SLC-40  28.563197  -80.576820      0

In [12]:
m = folium.Map(location = nasa_coordinate, zoom_start = 10)

ss_map = plugins.MarkerCluster().add_to(m)

for lat, long, region, outcome in zip(spacex_df['Lat'], spacex_df['Long'], spacex_df['Launch Site'], spacex_df['class']):
    folium.Marker(
        location = [lat, long],
        icon = folium.Icon(color='green' if outcome == 1 else 'red'),
        popup = region,
    ).add_to(ss_map)

In [13]:
m

In [14]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

m.add_child(mouse_position)
m